name: nanoid
version: 0.0.2
author: Rongjian Zhang <pd4d10@gmail.com>
description: A tiny, secure, URL-friendly, unique string ID generator
homepage: https://github.com/pd4d10/nanoid

environment:
  sdk: ">=2.0.0-dev.32.0 <2.0.0"

dev_dependencies:
  test: ^0.12.33
